database:
  postgressql: postgres://qwerty:qwerty@localhost:5438/postgres?sslmode=disable
  max-attempts: 5

server:
  host: localhost
  port: 5050

token:
  secret-key: secret-key
  access-time-live-token: 5s
  user-key: user-key